### ISSUE TITLE
[Bug]Error 500 when try to delete old version of torrents

### ISSUE THREAD

**Issue by Gideon75** [HDVinnie/UNIT3D#1950]
**Describe the bug**
Error 500 when try to delete old version of torrents

**To Reproduce**
1. Go to similar torrent
2. Click torrents you wont delete
3. See error

**Screenshots**
https://gyazo.com/f87bc73765a20bdcf556585771edd9f5

PHP
Currently Running
php8.0.11
DATABASE
Currently Running
8.0.26-0ubuntu0.20.04.3
LARAVEL
Currently Running
Ver. 8.61.0

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: all

**Possible Fix?**
Seems like maybe the torrent your trying to delete does have a TMDB id or it’s is wrong Id
[laravel-2021-10-15.log](https://github.com/HDInnovations/UNIT3D-Community-Edition/files/7357253/laravel-2021-10-15.log)

**Comment by HDVinnie** [comment]
Maybe the torrent your trying to delete doesn't have a TMDB id or it’s is wrong Id? Cann confirm before I fix please?

**Comment by HDVinnie** [comment]
@clandestine8 can you look over this?

**Comment by Gideon75** [comment]
the link above is another
