### ISSUE TITLE
[Bug] Featured Game Torrents

### ISSUE THREAD

**Issue by kREATUr67** [HDVinnie/UNIT3D#1966]
**Describe the bug**
error 500 in home view when promoting game torrent

**To Reproduce**

1.  After fantastic changes in bug fix #1946 through this fine, gorgeous developer checked again to promote a game torrent.
     unfortunately leads to an error 500 on the home view

![error 500](https://user-images.githubusercontent.com/67836615/138752329-898ab3db-1ca9-4719-9dd6-c01d94959358.jpg)

Error shown in laravel log is:

`Call to a member function isNotEmpty() on array (View: /var/www/html/resources/views/blocks/featured.blade.php) {"view":{"view":"/var/www/html/resources/views/blocks/featured.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-119625844 data-indent-pad=\" \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#987</a><samp data-depth=1 class=sf-dump-expanded>`

**Expected behavior**
would be nice if promoting game torrents would be great

**Screenshots**
see above.

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.3.0
- Laravel Version: Ver. 8.61.0
- PHP Version: php8.0.11
- Database Driver & Version: 8.0.26-0ubuntu0.20.04.3
- Web Server Driver & Version: nginx: master
- OS Driver and Version: ubuntu 20.04.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome, Opera etc.
 - Version: newest

**Comment by hucstar** [comment]
Oh I am having the same problem!

**Comment by hucstar** [comment]
I pulled and used the latest code but the problrm is still exists.  Only when I remove the game torrent does the home page return to normal. @HDVinnie

**Comment by hucstar** [comment]
Maybe it’s because of the old seed before updating the code, so it shouldn’t be a problem to redistribute now. Sorry to interrupt

> I pulled and used the latest code but the problrm is still exists. Only when I remove the game torrent does the home page return to normal. @HDVinnie
Maybe it’s because of the old torrent before updating the code. now there should be no problem to redistribute . Sorry to interrupt.

**Comment by kREATUr67** [comment]
The fix 100% working. Did you change all files in fix #1946 . May be its only working when you also built in both fixes.
