### ISSUE TITLE
[Bug] Create Forum Topic Button gone

### ISSUE THREAD

**Issue by Obi-Wana** [HDVinnie/UNIT3D#1967]
**Describe the bug**
Even though the permissions allow a user to create new topics, the "Create" button is gone on UNIT3D.SITE:
[IMG](https://ibb.co/68JXwS4)

**To Reproduce**
1. Go to 'Forums' where you have permissions to create topics
2. See the button is not there

**Comment by hucstar** [comment]
I see this discussion closed in 2021, but I have the same problem in 2024 today.
