### ISSUE TITLE
[Bug] 7.x.x, Attempt to read property "timestamp" on null

### ISSUE THREAD

**Issue by LostRager** [HDVinnie/UNIT3D#2709]
### UNIT3D Version

7.x.x

### PHP & Platform

8.2.4

### Laravel verion

10.7.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

.

### Description

I know 7.x.x is not ready, just testing stuff. 

When the torrent announces you get this error in the logs

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/901ab78d9c5d7b2d3f514bdcabf340d8590f97ee/app/Jobs/ProcessAnnounce.php#L105-L110

### Stack trace & logs

```shell
Attempt to read property "timestamp" on null {"exception":"[object] (ErrorException(code: 0): Attempt to read property \"timestamp\" on null at /var/www/html/app/Jobs/ProcessAnnounce.php:106)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/app/Jobs/ProcessAnnounce.php(106): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\ProcessAnnounce->handle()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Middleware/WithoutOverlapping.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Queue\\Middleware\\WithoutOverlapping->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(434): Illuminate\\Queue\\Jobs\\Job->fire()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(384): Illuminate\\Queue\\Worker->process()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(175): Illuminate\\Queue\\Worker->runJob()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(136): Illuminate\\Queue\\Worker->daemon()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(119): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\\Container\\Container->call()
#30 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\\Component\\Console\\Command\\Command->run()
#32 /var/www/html/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#33 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#34 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
#36 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#37 {main}
"}
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
Solved

**Comment by LostRager** [comment]
If you pause and unpause the torrent you get the error: `unexpected end of file in bencoded string` in the torrent client.

No errors in the laravel log.

**Comment by Roardom** [comment]
> With the fix, If you pause and/or unpause the torrent you get the error: `unexpected end of file in bencoded string` in the torrent client.
> 
> No errors in the laravel log.

Seems unrelated, also very vague. It basically means that the tracker response wasn't bencoded or the bencode it returned wasn't valid. What response are you getting via curl?

**Comment by LostRager** [comment]
> 

Not quite sure how to use curl, but i removed all the bin2hex and hex2bin's from:

 https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/9c6405382c665ef45f57f1dd3ce1a4fe83f62750/app/Http/Controllers/AnnounceController.php#L384-L406
 
 and
 
 https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/9c6405382c665ef45f57f1dd3ce1a4fe83f62750/app/Http/Controllers/AnnounceController.php#L293-L294
 
 And the error goes away.

**Comment by Roardom** [comment]
Regarding curl, something like this should work:

```sh
curl "http://domain.tld/announce/[insert passkey here]?info_hash=z%8B%83%9Fx%C3%1D%E7%14%FF%F4%B2%40%27V%BB%05%A6~%0F&peer_id=01234567890123456789&port=1&uploaded=0&downloaded=0&left=0&event=started&numwant=50&compact=1"
```
with the info_hash containing the 20-byte percent encoded info_hash. It should return the bencoded string.

**Comment by LostRager** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/9c6405382c665ef45f57f1dd3ce1a4fe83f62750/app/Http/Controllers/AnnounceController.php#L388

Should that be hex2bin? Since its returning the id? with hex2bin it returns nothing and without it returns the id.
![image](https://user-images.githubusercontent.com/5929772/233589219-3b423a5c-fbed-4a2a-b2b9-ad8021e94f86.png)

**Comment by Roardom** [comment]
It just has to be identical to the line 20 lines below it. One sets it, one gets it. 

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/9c6405382c665ef45f57f1dd3ce1a4fe83f62750/app/Http/Controllers/AnnounceController.php#L405

**Comment by Roardom** [comment]
https://redis.io/commands/hset/
https://redis.io/commands/hget/

**Comment by LostRager** [comment]
i see, 

Here is the result from curl `d8:completei1e10:incompletei0e8:intervali3640e12:min intervali3600e5:peers0:6:peers60:e`

**Comment by Roardom** [comment]
That first result is expected. You always receive a response however, and that could be the result of that bencode error message. However, I'm unable to reproduce when repeating an announce a second time.

**Comment by LostRager** [comment]
You were not able to reproduce?

very strange.

I reinstalled and used a fresh db instead of a dump. still the same issue.

**Comment by Roardom** [comment]
Hmm, strange. I was using a fresh db too. I'll have to give it another go in a little bit.

**Comment by Roardom** [comment]
Think we managed to narrow it down to a rogue config setting. Can you give this a try: https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/45dbf0849bd49cbc8bfdea5d01776eebea46697e

**Comment by LostRager** [comment]
I was already running predis. So this fix did not solve the issue, sadly.

**Comment by LostRager** [comment]
Okay i figured it out:

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/45dbf0849bd49cbc8bfdea5d01776eebea46697e/app/Http/Controllers/AnnounceController.php#L443

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/45dbf0849bd49cbc8bfdea5d01776eebea46697e/app/Http/Controllers/AnnounceController.php#L460

These lines do not need to be decoded. As the response is not encoded.

**Comment by HDVinnie** [comment]
Im not sure that's right as it is indeed encoded

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/45dbf0849bd49cbc8bfdea5d01776eebea46697e/app/Http/Controllers/AnnounceController.php#L296-L297

**Comment by LostRager** [comment]
> Im not sure that's right as it is indeed encoded
> 
> https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/45dbf0849bd49cbc8bfdea5d01776eebea46697e/app/Http/Controllers/AnnounceController.php#L296-L297

Yes, i noticed i got a response now, just not the right one.

**Comment by LostRager** [comment]
Its super wierd how it cant be replicated...

I've think ive gotten too the cause tho. Its not getting past the min lock check

**Comment by HDVinnie** [comment]
```
            // Lock Min Announce Interval.
            /*if (config('announce.min_interval.enabled')) {
                $this->checkMinInterval($torrent, $queries, $user);
            }*/
```

If you comment it out does announce work for you?

**Comment by LostRager** [comment]
> ```
>             // Lock Min Announce Interval.
>             /*if (config('announce.min_interval.enabled')) {
>                 $this->checkMinInterval($torrent, $queries, $user);
>             }*/
> ```
> 
> If you comment it out does announce work for you?

yes

**Comment by HDVinnie** [comment]
Interesting. I think I have faced this before myself. Mind opening a new issue regarding `checkMinInterval`?

**Comment by LostRager** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/2715
