### ISSUE TITLE
Repo has no code

### ISSUE THREAD

**Issue by azacock** [HDVinnie/UNIT3D#3]
The repo has no code.

## Expected Behavior
I open the repo and see the code.

## Current Behavior
I open the repo and see no code.

## Possible Solution
Upload code.

## Steps to Reproduce (for bugs)
Live example: https://github.com/HDVinnie/UNIT3D
1. Visit repo
2. Observe lack of code

## Context
I am trying to view the code, but there is no code so I can't view the code.

## Your Environment
Linux 4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64 GNU/Linux
Running GNU IceCat 45.7.0.

**Comment by HDVinnie** [comment]
The initial public release of UNIT3D has not yet been pushed. Its a few days out. Find out more on our discord server. 

https://discord.gg/T2YPNPZ

**Comment by azacock** [comment]
If you haven't released your code why do you have a repo? What's the point of a repo without code? Please fix this production-critical bug immediately.

**Comment by spaghetti2514** [comment]
If the code has not yet been pushed, then this issue has not been resolved and should not be closed

**Comment by HDVinnie** [comment]
see 4244d20039ad27439e77fb7ea4f2a208b232c0ec
