### ISSUE TITLE
(Enhancement) Add support for TPDB as a metadata agent for XXX

### ISSUE THREAD

**Issue by dsrtusr88** [HDVinnie/UNIT3D#3339]
https://api.metadataapi.net/docs/

The Porn DB is a functioning user curated/web crawling DB that is used by Whisparr-v2 as its metadata source.  If incorporated, it would allow UNIT3D sites that allow XXX content to actually slot XXX scenes releases for the first time ever.  Would not recommend getting off TMDB for XXX movies.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3339">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3339/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3339/pledge.svg">
</picture>
</a>

**Comment by bitappend** [comment]
I welcome this endeavor

**Comment by HDVinnie** [comment]
Transferred tro discussions. Issue board is for bugs only.
