### ISSUE TITLE
Building does not work

### ISSUE THREAD

**Issue by LaserEyess** [HDVinnie/UNIT3D#4]
Hi the README makes this seem like a well thought out and revolutionary project, so I wanted to try and build it, but I'm stuck and I'd like some help. I figured out steps 1 and 2, but I can't quite get step 3 right. I try to "go to the script dir" but it doesn't exist. I tried skipping that and going straight to step 4 but I can't find `config/` or any of the files in that directory. 

I must be doing something wrong, but I can't figure out what.

**Comment by HDVinnie** [comment]
closed see 4244d20039ad27439e77fb7ea4f2a208b232c0ec

**Comment by azacock** [comment]
Please do not close unresolved issues. Do you at least have a workaround?

**Comment by LaserEyess** [comment]
Very disappointing. I'm having second thoughts about this project. Please commit the source code ASAP.

**Comment by HDVinnie** [comment]
you guys can troll all you want....it wont hurt me. Just shows your worried about the survival of https://git.oppaiti.me/Oppaitime/Gazelle , your own codebase.
