### ISSUE TITLE
Readme has spelling mistakes

### ISSUE THREAD

**Issue by ApexWeed** [HDVinnie/UNIT3D#5]
>php-gettext -> This is primarly for phpmyadmin, if **your** going to use it, there has been cases where it does not install when installing phpmyadmin.

This should be you're.

**Comment by HDVinnie** [comment]
Thank you for the report. I will fix it and push the updated read me revision went home.

**Comment by ApexWeed** [comment]
Comment also has a spelling mistake.

**Comment by HDVinnie** [comment]
Closed 0a49d916a7e5e5918c807297f18ca78055a56c60
