### ISSUE TITLE
Incorrect issue template

### ISSUE THREAD

**Issue by VirtualURL** [HDVinnie/UNIT3D#7]
> Environment name and version (e.g. Chrome 39, Ubuntu?):
Operating System and version (desktop or mobile?):

example of operating system is "Ubuntu" which i assume is a spelling error.
it should read "Ubuntu GNU/Linux".

**Comment by HDVinnie** [comment]
It's a base template I grabbed off the web. Revisions will come. Or feel free to make a PR.

**Comment by HDVinnie** [comment]
83832e7c7fbcb60b2f8bfca485d898d97171cf60
